version: "3"
services:
    web:
        build: .
        ports:
            - "8000:7001"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "P@ssword1!"
            ACCEPT_EULA: "Y"